# Create a new config file when a new docker image is built

name: Configure K8s

on:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Config overview
        run: |
          echo "Creating new config build for container ${{ github.event.client_payload.new_container }}"
          echo "Starting build..."
